In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")

3.12

In [3]:
os.getcwd()
os.chdir('a:\\Dominic\\My Projects\\Home Credit\\')

In [4]:
Bureau = pd.read_csv('data/External/bureau.csv')

In [5]:
BureauBal = pd.read_csv('data/External/bureau_balance.csv')

In [6]:
Bureau.dtypes

SK_ID_CURR                  int64
SK_ID_BUREAU                int64
CREDIT_ACTIVE              object
CREDIT_CURRENCY            object
DAYS_CREDIT                 int64
CREDIT_DAY_OVERDUE          int64
DAYS_CREDIT_ENDDATE       float64
DAYS_ENDDATE_FACT         float64
AMT_CREDIT_MAX_OVERDUE    float64
CNT_CREDIT_PROLONG          int64
AMT_CREDIT_SUM            float64
AMT_CREDIT_SUM_DEBT       float64
AMT_CREDIT_SUM_LIMIT      float64
AMT_CREDIT_SUM_OVERDUE    float64
CREDIT_TYPE                object
DAYS_CREDIT_UPDATE          int64
AMT_ANNUITY               float64
dtype: object

In [7]:
Bureau = Bureau.astype({'SK_ID_CURR': 'string', 'SK_ID_BUREAU': 'string'})

In [8]:
Bureau['CREDIT_TYPE'].value_counts(dropna=False)

CREDIT_TYPE
Consumer credit                                 1251615
Credit card                                      402195
Car loan                                          27690
Mortgage                                          18391
Microloan                                         12413
Loan for business development                      1975
Another type of loan                               1017
Unknown type of loan                                555
Loan for working capital replenishment              469
Cash loan (non-earmarked)                            56
Real estate loan                                     27
Loan for the purchase of equipment                   19
Loan for purchase of shares (margin lending)          4
Mobile operator loan                                  1
Interbank credit                                      1
Name: count, dtype: int64

In [9]:
Bureau[Bureau['AMT_CREDIT_SUM_LIMIT']>0]['CREDIT_TYPE'].value_counts(dropna=False)

CREDIT_TYPE
Credit card        74119
Consumer credit       26
Car loan              10
Name: count, dtype: int64

In [10]:
Bureau.sample(25)

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
252220,287834,5901022,Active,currency 1,-1062,0,764.0,NaN,NaN,0,2914060.50,1153579.5,0.000,0.0,Car loan,-24,52006.5
722009,270819,6495479,Active,currency 1,-106,0,69.0,NaN,NaN,0,19710.00,13644.0,0.000,0.0,Consumer credit,-30,NaN
483600,150550,6135263,Active,currency 1,-1220,0,119.0,NaN,NaN,0,445500.00,63940.5,0.000,0.0,Consumer credit,-30,13293.0
1243518,140563,5958788,Closed,currency 1,-1273,0,-1183.0,-1128.0,NaN,0,101227.50,NaN,NaN,0.0,Consumer credit,-1125,0.0
223298,199819,5712295,Closed,currency 1,-933,0,-567.0,-657.0,0.0,0,164016.00,0.0,0.000,0.0,Consumer credit,-657,NaN
1364425,329935,5414116,Active,currency 1,-105,0,NaN,NaN,0.0,0,135000.00,87003.0,44296.335,0.0,Credit card,-15,NaN
434250,416513,5513195,Closed,currency 1,-1885,0,-1520.0,-1618.0,NaN,0,36000.00,0.0,0.000,0.0,Credit card,-1616,0.0
441884,218287,6524805,Closed,currency 1,-1689,0,-1377.0,-1377.0,0.0,0,203220.00,NaN,NaN,0.0,Consumer credit,-1375,NaN
275442,172945,5060769,Closed,currency 1,-1980,0,-1890.0,-1943.0,NaN,0,18630.00,0.0,0.000,0.0,Consumer credit,-1745,0.0
320512,130187,5531141,Closed,currency 1,-1832,0,-1650.0,-1650.0,0.0,0,27585.00,0.0,0.000,0.0,Consumer credit,-1505,NaN
1161061,455007,5907500,Active,currency 1,-332,0,1492.0,NaN,0.0,0,585000.00,519165.0,0.000,0.0,Consumer credit,-30,14823.0
312938,137283,6106007,Active,currency 1,-617,0,10340.0,NaN,9526.5,0,173250.00,NaN,NaN,0.0,Credit card,-17,NaN
460915,380297,5043357,Closed,currency 1,-615,0,-414.0,-414.0,0.0,0,0.00,0.0,0.000,0.0,Credit card,-414,NaN
1346292,234288,6625814,Active,currency 1,-155,0,NaN,NaN,0.0,0,405000.00,0.0,405000.000,0.0,Credit card,-11,NaN
1370152,307951,6712561,Active,currency 1,-308,0,422.0,NaN,NaN,0,606060.00,449131.5,0.000,0.0,Consumer credit,-67,NaN
602520,389365,5146953,Active,currency 1,-621,0,NaN,NaN,11214.0,0,450000.00,447291.0,2709.000,0.0,Credit card,-29,NaN
769171,235348,6349332,Closed,currency 1,-1573,0,-1361.0,-1449.0,NaN,0,56551.50,0.0,NaN,0.0,Consumer credit,-707,NaN
1418976,229181,6174907,Closed,currency 1,-2089,0,-1868.0,-1868.0,NaN,0,31230.00,0.0,NaN,0.0,Consumer credit,-1166,57600.0
1587218,301992,5585613,Active,currency 1,-94,0,1551.0,NaN,NaN,0,337500.00,330327.0,0.000,0.0,Consumer credit,-29,8293.5
229427,213167,5844050,Closed,currency 1,-752,0,-538.0,-566.0,NaN,0,37314.72,0.0,NaN,0.0,Consumer credit,-564,NaN
1481997,319050,6109004,Closed,currency 1,-1158,0,-1127.0,-1117.0,NaN,0,72360.00,0.0,0.000,0.0,Consumer credit,-861,9585.0
660621,138900,6100625,Closed,currency 1,-1963,0,-867.0,-1219.0,NaN,0,315000.00,0.0,0.000,0.0,Consumer credit,-585,0.0
1003738,368681,5456411,Closed,currency 1,-551,0,-431.0,-419.0,NaN,0,82539.00,NaN,NaN,0.0,Consumer credit,-413,NaN
1471606,179396,5979275,Closed,currency 1,-1726,0,-1422.0,-1449.0,NaN,0,126008.28,0.0,NaN,0.0,Consumer credit,-843,NaN
1419415,261764,6175453,Closed,currency 1,-1005,0,-942.0,-942.0,NaN,0,43803.00,0.0,0.000,0.0,Consumer credit,-731,13500.0

In [11]:
Bureau.sample(20)[['SK_ID_BUREAU','CREDIT_ACTIVE','CREDIT_TYPE','AMT_CREDIT_SUM_LIMIT', 'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT']]

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_TYPE,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT
1648412,5559574,Active,Consumer credit,0.00,55584.00,55584.0
110092,6027532,Closed,Consumer credit,0.00,900000.00,0.0
348298,6101994,Closed,Consumer credit,0.00,59764.50,0.0
434743,5936852,Closed,Consumer credit,0.00,80955.00,0.0
1164094,6195196,Closed,Consumer credit,0.00,90846.00,0.0
1213295,5641123,Closed,Consumer credit,NaN,39411.00,0.0
1191682,5294365,Closed,Consumer credit,0.00,522000.00,0.0
75650,5253471,Active,Consumer credit,0.00,68495.04,0.0
369755,5545004,Closed,Consumer credit,NaN,23769.00,0.0
454157,5035144,Sold,Mortgage,NaN,4468500.00,0.0
176843,5701412,Closed,Consumer credit,0.00,101893.50,0.0
1489022,5623535,Closed,Consumer credit,NaN,163404.00,NaN
1403425,5115893,Active,Car loan,0.00,675000.00,348097.5
63579,5002472,Closed,Consumer credit,NaN,109662.30,0.0
921511,6251067,Active,Consumer credit,0.00,105210.00,89599.5
791651,6503064,Active,Credit card,450000.00,450000.00,0.0
1477246,5350041,Active,Credit card,5859.09,159750.00,153886.5
607339,6466162,Closed,Credit card,0.00,0.00,0.0
202549,5833331,Active,Credit card,0.00,432000.00,259654.5
732232,6377519,Active,Mortgage,0.00,2385000.00,1719904.5

Here is the correct way to interpret the variables for a credit card:

- AMT_CREDIT_SUM: This is the total credit limit on the card.

- AMT_CREDIT_SUM_DEBT: This is the current balance, or how much you owe.

- AMT_CREDIT_SUM_LIMIT: This is the available credit, or how much you can still spend.

In [12]:
Bureau['new'] = Bureau['AMT_CREDIT_SUM_DEBT'] + Bureau['AMT_CREDIT_SUM_LIMIT']

In [13]:
temp = Bureau[['SK_ID_BUREAU','CREDIT_ACTIVE','CREDIT_TYPE','AMT_CREDIT_SUM_LIMIT', 'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'new']]

In [14]:
temp2 = Bureau[(Bureau['CREDIT_ACTIVE']=='Active') & (Bureau['CREDIT_TYPE']=='Credit card')]
temp2['change'] = abs((temp2['new'] - temp2['AMT_CREDIT_SUM'])/temp2['AMT_CREDIT_SUM'])
temp2 = temp2[['SK_ID_BUREAU','CREDIT_ACTIVE','CREDIT_TYPE','AMT_CREDIT_SUM_LIMIT', 'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_OVERDUE', 'new', 'change']]

C:\Users\domjo\AppData\Local\Temp\ipykernel_38060\543197155.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2['change'] = abs((temp2['new'] - temp2['AMT_CREDIT_SUM'])/temp2['AMT_CREDIT_SUM'])

- For closed account (~ 1m) `AMT_CREDIT_SUM_LIMIT` and `AMT_CREDIT_SUM_DEBT` = 0 (mostly) 
- For active accounts (~ 600k) 
    - Consumer Credits (~ 300k) have zero  `AMT_CREDIT_SUM_LIMIT`
    - Credit Cards (~ 300k) 
        - 40k have `AMT_CREDIT_SUM` > 0 and `AMT_CREDIT_SUM_DEBT`= 0 and `AMT_CREDIT_SUM_LIMIT`=0.
        - 87k have > `AMT_CREDIT_SUM` = `AMT_CREDIT_SUM_DEBT` + `AMT_CREDIT_SUM_LIMIT`
        - 87k cases where `AMT_CREDIT_SUM` != `AMT_CREDIT_SUM_DEBT` + `AMT_CREDIT_SUM_LIMIT`
        - 1310 cases where `AMT_CREDIT_SUM` = 0 but `AMT_CREDIT_SUM_DEBT` > 0
        - 63k have > `AMT_CREDIT_SUM` and either of the two missing

In [15]:
# Set AMT_CREDIT_SUM_LIMIT to 0 for closed credits where it is null
Bureau.loc[(Bureau['CREDIT_ACTIVE'] == 'Closed') & (Bureau['AMT_CREDIT_SUM_LIMIT'].isnull()), 'AMT_CREDIT_SUM_LIMIT'] = 0

In [16]:
# Set AMT_CREDIT_SUM_DEBT to 0 for closed credits where it is null
Bureau.loc[(Bureau['CREDIT_ACTIVE'] == 'Closed') & (Bureau['AMT_CREDIT_SUM_DEBT'].isnull()), 'AMT_CREDIT_SUM_DEBT'] = 0

In [17]:
Bureau.loc[(Bureau['CREDIT_ACTIVE'] == 'Active') & (Bureau['AMT_CREDIT_SUM_LIMIT'].isnull()) & (Bureau['CREDIT_TYPE'] != 'Credit card'), 'AMT_CREDIT_SUM_LIMIT'] = 0

Calculate utilization rate for Credit cards to determine the average debit amount.

In [18]:
temp2['UtilzRate'] = np.where(temp2['AMT_CREDIT_SUM']>0, temp2['AMT_CREDIT_SUM_DEBT'] / temp2['AMT_CREDIT_SUM'], np.nan)

In [19]:
Bureau['UtilzRate'] = np.where(Bureau['AMT_CREDIT_SUM']>0, Bureau['AMT_CREDIT_SUM_DEBT'] / Bureau['AMT_CREDIT_SUM'], np.nan)

In [20]:
Bureau['Duration'] = Bureau['DAYS_CREDIT_ENDDATE'] - Bureau['DAYS_CREDIT']

In [21]:
Bureau['OverDraftFlag'] = 1 * (Bureau['AMT_CREDIT_SUM_DEBT'] > Bureau['AMT_CREDIT_SUM'])

In [22]:
Bureau['AnnuityPercent'] = np.where(Bureau['AMT_CREDIT_SUM_DEBT']>0, Bureau['AMT_ANNUITY'] / Bureau['AMT_CREDIT_SUM_DEBT'], np.nan)

In [23]:
def get_utilization_rate(x, fulldf):
    y = fulldf.loc[x.index]
    y = y[y['CREDIT_ACTIVE'] == 'Active']
    return np.mean(np.where(
                                y['AMT_CREDIT_SUM'] > 0,
                                y['AMT_CREDIT_SUM_DEBT'] / y['AMT_CREDIT_SUM'],
                                np.nan
                            ) )

 Bureau Balance

In [25]:
BureauBal.dtypes

SK_ID_BUREAU       int64
MONTHS_BALANCE     int64
STATUS            object
dtype: object

In [26]:
BureauBal = BureauBal.astype({'SK_ID_BUREAU': 'string'})

In [27]:
BureauBal.sort_values(by=['SK_ID_BUREAU', 'MONTHS_BALANCE'], inplace=True)

In [28]:
BureauBal.head(20)

         SK_ID_BUREAU  MONTHS_BALANCE STATUS
26079849      5001709             -96      X
26079848      5001709             -95      X
26079847      5001709             -94      X
26079846      5001709             -93      X
26079845      5001709             -92      X
26079844      5001709             -91      X
26079843      5001709             -90      X
26079842      5001709             -89      X
26079841      5001709             -88      X
26079840      5001709             -87      X
26079839      5001709             -86      X
26079838      5001709             -85      C
26079837      5001709             -84      C
26079836      5001709             -83      C
26079835      5001709             -82      C
26079834      5001709             -81      C
26079833      5001709             -80      C
26079832      5001709             -79      C
26079831      5001709             -78      C
26079830      5001709             -77      C

In [29]:
BureauBal['STATUS'].value_counts(dropna=False)

STATUS
C    13646993
0     7499507
X     5810482
1      242347
5       62406
2       23419
3        8924
4        5847
Name: count, dtype: int64

In [30]:
BureauBal['STATUS_FILLED'] = BureauBal.groupby('SK_ID_BUREAU')['STATUS'].transform(
    lambda x: x.replace('X', np.nan).ffill(limit=3).bfill(limit=3)
)

C:\Users\domjo\AppData\Local\Temp\ipykernel_38060\2127701334.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lambda x: x.replace('X', np.nan).ffill(limit=3).bfill(limit=3)

In [31]:
BureauBal.groupby('SK_ID_BUREAU').last()#.reset_index()[['SK_ID_BUREAU', 'STATUS']].value_counts(dropna=False)

              MONTHS_BALANCE STATUS STATUS_FILLED
SK_ID_BUREAU
5001709                    0      C             C
5001710                    0      C             C
5001711                    0      X             0
5001712                    0      C             C
5001713                    0      X          None
...                      ...    ...           ...
6842884                    0      C             C
6842885                    0      5             5
6842886                    0      C             C
6842887                    0      C             C
6842888                    0      C             C

[817395 rows x 3 columns]

In [32]:
BureauBal[BureauBal['SK_ID_BUREAU']=='5001711']

        SK_ID_BUREAU  MONTHS_BALANCE STATUS STATUS_FILLED
2846402      5001711              -3      0             0
2846401      5001711              -2      0             0
2846400      5001711              -1      0             0
2846399      5001711               0      X             0

In [33]:
BureauBal['STATUS_FILLED'].value_counts(dropna=False)

STATUS_FILLED
C      13735833
0       8705656
NaN     4488360
1        260330
5         67892
2         25590
3          9496
4          6768
Name: count, dtype: int64

In [42]:
BureauBal_Silver = BureauBal.groupby('SK_ID_BUREAU').agg(
    Duration_Balance=('MONTHS_BALANCE', lambda x: x.max() - x.min()),
    BureauBal_Last_Status=('STATUS_FILLED', 'last'),
    BureauBal_Days_With_NoDPD=('STATUS_FILLED', lambda x: sum(x == '0')),
 #  BureauBalDaysWithNoDPDRatio=('STATUS_FILLED', lambda x: sum(x == '0') / (x.max() - x.min())),
    BureauBal_Days_In_DPD1=('STATUS_FILLED', lambda x: sum(x == '1')),
    BureauBal_Days_In_DPD2=('STATUS_FILLED', lambda x: sum(x == '2')),
    BureauBal_Days_In_DPD3=('STATUS_FILLED', lambda x: sum(x == '3')),
    BureauBal_Days_In_DPD4=('STATUS_FILLED', lambda x: sum(x == '4')),
    BureauBal_Days_In_DPD5=('STATUS_FILLED', lambda x: sum(x == '5'))
).reset_index()

In [43]:
BureauBal_Silver['BureauBal_Days_In_DPD_ge1'] = BureauBal_Silver['BureauBal_Days_In_DPD1'] + BureauBal_Silver['BureauBal_Days_In_DPD2'] + BureauBal_Silver['BureauBal_Days_In_DPD3'] + BureauBal_Silver['BureauBal_Days_In_DPD4'] + BureauBal_Silver['BureauBal_Days_In_DPD5']

In [44]:
BureauBal_Silver['BureauBal_Days_In_DPD_ge4'] = BureauBal_Silver['BureauBal_Days_In_DPD4'] + BureauBal_Silver['BureauBal_Days_In_DPD5']

In [45]:
Bureau_Bronze = Bureau.merge(
    BureauBal_Silver,
    how='left',
    left_on='SK_ID_BUREAU',
    right_on='SK_ID_BUREAU'
)

In [46]:
Bureau_Silver = Bureau_Bronze.groupby('SK_ID_CURR').agg(

    Bureau_Total_Credit_Count=('SK_ID_BUREAU', 'count'),
    
    Bureau_Credit_Type_Total_Count=('CREDIT_TYPE', 'nunique'),
    Bureau_ConsumerCredit_Count= ('CREDIT_TYPE', lambda x: sum(x == 'Consumer credit')),
    Bureau_CreditCard_Count= ('CREDIT_TYPE', lambda x: sum(x == 'Credit card')),
    Bureau_CarLoan_Count= ('CREDIT_TYPE', lambda x: sum(x == 'Car loan')),
    Bureau_Mortgage_Count= ('CREDIT_TYPE', lambda x: sum(x == 'Mortgages')),

    Bureau_Total_Active_Credit_Count=('SK_ID_BUREAU', lambda x: sum(Bureau.loc[x.index, 'CREDIT_ACTIVE'] == 'Active')),
    Bureau_Past_Bad_Credit_Count=('SK_ID_BUREAU', lambda x: sum(Bureau.loc[x.index, 'CREDIT_ACTIVE'] == 'Bad debt')),
    Bureau_Past_Sold_Credit_Count=('SK_ID_BUREAU', lambda x: sum(Bureau.loc[x.index, 'CREDIT_ACTIVE'] == 'Sold')),

    Bureau_Days_To_Last_Credit=('DAYS_CREDIT', 'max'),
    Bureau_Avg_Days_To_Credit=('DAYS_CREDIT', lambda x: x.sort_values(ascending=True).diff().mean() ),
    Bureau_Avg_Duration=('Duration', 'mean'),
    Bureau_Max_Days_Credit_End=('DAYS_CREDIT_ENDDATE', 'max'),

    Bureau_Is_Past_Overdue_Flag=('CREDIT_DAY_OVERDUE', lambda x: (x > 0).any() * 1),
    Bureau_Active_Utilization_Ratio=('UtilzRate', 'mean'),    

    Bureau_Max_Credit_Overdue_Amount=('AMT_CREDIT_MAX_OVERDUE', 'max'),
    Bureau_Avg_Credit_Amount=('AMT_CREDIT_SUM', 'mean'),
    Bureau_Avg_Credit_Debt_Amount=('AMT_CREDIT_SUM_DEBT', 'mean'),
    Bureau_Overdraft_Flag_Count = ('OverDraftFlag', 'sum'),
    Bureau_Avg_Annuity_Percent=('AnnuityPercent', 'mean'),

  # BureauBalLastStatusDPD5Flag=('BureauBalLastStatus', lambda x: (x == '5').any() * 1),
    BureauBal_Last_Status_DPD_gt_90_ID_Flag=('BureauBal_Last_Status', lambda x: (x.isin(['4','5']).any() * 1)),
    BureauBal_Last_Status_DPD_gt_90_ID_Count=('BureauBal_Last_Status', lambda x: sum(x.isin(['4','5']) * 1)),

    BureauBal_Days_In_DPD_gt_90_ID_Count=('BureauBal_Days_In_DPD_ge4', lambda x: sum((x > 0)*1)),
    BureauBal_Days_In_DPD_gt_90_Days_Count=('BureauBal_Days_In_DPD_ge4', 'sum'),

    BureauBal_Days_In_DPD_gt_0_ID_Count=('BureauBal_Days_In_DPD_ge1', lambda x: sum((x > 0)*1)),
    BureauBal_Days_In_DPD_gt_0_Days_Count=('BureauBal_Days_In_DPD_ge1', 'sum'),
)