In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
os.getcwd()
os.chdir('a:\\Dominic\\My Projects\\Home Credit\\')

In [3]:
CCBal = pd.read_csv('data/Internal/credit_card_balance.csv')

In [4]:
CCBal = CCBal.astype({'SK_ID_CURR': 'string', 'SK_ID_PREV': 'string'})
CCBal.dtypes

SK_ID_PREV                    string[python]
SK_ID_CURR                    string[python]
MONTHS_BALANCE                         int64
AMT_BALANCE                          float64
AMT_CREDIT_LIMIT_ACTUAL                int64
AMT_DRAWINGS_ATM_CURRENT             float64
AMT_DRAWINGS_CURRENT                 float64
AMT_DRAWINGS_OTHER_CURRENT           float64
AMT_DRAWINGS_POS_CURRENT             float64
AMT_INST_MIN_REGULARITY              float64
AMT_PAYMENT_CURRENT                  float64
AMT_PAYMENT_TOTAL_CURRENT            float64
AMT_RECEIVABLE_PRINCIPAL             float64
AMT_RECIVABLE                        float64
AMT_TOTAL_RECEIVABLE                 float64
CNT_DRAWINGS_ATM_CURRENT             float64
CNT_DRAWINGS_CURRENT                   int64
CNT_DRAWINGS_OTHER_CURRENT           float64
CNT_DRAWINGS_POS_CURRENT             float64
CNT_INSTALMENT_MATURE_CUM            float64
NAME_CONTRACT_STATUS                  object
SK_DPD                                 int64
SK_DPD_DEF                             int64
dtype: object

In [5]:
CCBal.head(20)

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.500,0.0,877.500,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.000,0.0,0.000,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.000,0.0,0.000,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.000,0.0,0.000,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.000,0.0,11547.000,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
5,2646502,380010,-7,82903.815,270000,0.0,0.000,0.0,0.000,4449.105,...,82773.315,82773.315,0.0,0,0.0,0.0,2.0,Active,7,0
6,1079071,171320,-6,353451.645,585000,67500.0,67500.000,0.0,0.000,14684.175,...,351881.145,351881.145,1.0,1,0.0,0.0,6.0,Active,0,0
7,2095912,118650,-7,47962.125,45000,45000.0,45000.000,0.0,0.000,0.000,...,47962.125,47962.125,1.0,1,0.0,0.0,51.0,Active,0,0
8,2181852,367360,-4,291543.075,292500,90000.0,289339.425,0.0,199339.425,130.500,...,286831.575,286831.575,3.0,8,0.0,5.0,3.0,Active,0,0
9,1235299,203885,-5,201261.195,225000,76500.0,111026.700,0.0,34526.700,6338.340,...,197224.695,197224.695,3.0,9,0.0,6.0,38.0,Active,0,0
10,1108284,209660,-7,102076.560,180000,92250.0,92250.000,0.0,0.000,0.000,...,94224.060,94224.060,5.0,5,0.0,0.0,0.0,Active,0,0
11,2740914,340339,-1,131669.145,225000,10800.0,10800.000,0.0,0.000,6000.480,...,127891.935,127891.935,2.0,2,0.0,0.0,6.0,Active,0,0
12,1985699,302517,-4,1427.265,135000,4500.0,101304.720,0.0,96804.720,3023.955,...,0.000,0.000,1.0,30,0.0,29.0,27.0,Active,0,0
13,1441883,171537,-5,0.000,270000,0.0,0.000,0.0,0.000,12218.490,...,0.000,0.000,0.0,0,0.0,0.0,2.0,Active,0,0
14,1864742,303581,-1,0.000,45000,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,59.0,Active,0,0
15,2037377,289902,-1,131294.340,135000,0.0,0.000,0.0,0.000,6774.660,...,131294.340,131294.340,0.0,0,0.0,0.0,11.0,Active,0,0
16,1816636,255981,-6,72899.955,450000,67500.0,67500.000,0.0,0.000,2457.720,...,71554.455,71554.455,1.0,1,0.0,0.0,42.0,Active,0,0
17,1039039,276642,-6,0.000,67500,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,33.0,Completed,0,0
18,2016842,302450,-3,0.000,0,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,2.0,Completed,0,0
19,1189095,231608,-4,452774.700,450000,9000.0,9000.000,0.0,0.000,22916.475,...,451429.200,451429.200,1.0,1,0.0,0.0,22.0,Active,0,0

In [6]:
CCBal.sort_values(by=['SK_ID_CURR', 'SK_ID_PREV', 'MONTHS_BALANCE'], ascending=[True, True, True], inplace=True)
CCBal = CCBal.reset_index(drop=True)

In [7]:
CCBal.groupby(['SK_ID_CURR','SK_ID_PREV'])[['SK_ID_CURR','SK_ID_PREV']].count()

                       SK_ID_CURR  SK_ID_PREV
SK_ID_CURR SK_ID_PREV
100006     1489396              6           6
100011     1843384             74          74
100013     2038692             96          96
100021     2594025             17          17
100023     1499902              8           8
...                           ...         ...
456244     2181926             41          41
456246     1079732              8           8
456247     1595171             95          95
456248     2743495             23          23
456250     1794451             12          12

[104307 rows x 2 columns]

Check Previous IDs to see if multiple active contracts occur at same time in last 24 months

In [8]:
# CCBal[(CCBal['SK_ID_CURR']=='120076')].sort_values(by=['SK_ID_PREV','MONTHS_BALANCE'])
CCBal[(CCBal['SK_ID_CURR']=='116511')].pivot(index='MONTHS_BALANCE', columns='SK_ID_PREV', values=['NAME_CONTRACT_STATUS','AMT_BALANCE'])

               NAME_CONTRACT_STATUS         AMT_BALANCE
SK_ID_PREV                  1324396 1578039     1324396     1578039
MONTHS_BALANCE
-26                             NaN  Active         NaN         0.0
-25                             NaN  Active         NaN         0.0
-24                             NaN  Active         NaN         0.0
-23                             NaN  Active         NaN  245281.545
-22                             NaN  Active         NaN  370750.545
-21                             NaN  Active         NaN  364336.065
-20                             NaN  Active         NaN  357556.725
-19                             NaN  Active         NaN  351322.785
-18                             NaN  Active         NaN   344243.52
-17                             NaN  Active         NaN     2632.14
-16                             NaN  Active         NaN         0.0
-15                             NaN  Active         NaN         0.0
-14                             NaN  Active         NaN         0.0
-13                             NaN  Active         NaN         0.0
-12                          Signed  Active         0.0         0.0
-11                          Active  Active         0.0         0.0
-10                          Active  Active         0.0         0.0
-9                           Active  Active         0.0         0.0
-8                           Active  Active         0.0         0.0
-7                           Active  Active         0.0         0.0
-6                           Active  Active         0.0         0.0
-5                           Active  Active         0.0         0.0
-4                           Active  Active         0.0         0.0
-3                           Active  Active         0.0         0.0
-2                           Active  Active         0.0         0.0
-1                           Active  Active         0.0         0.0

In [16]:
temp = CCBal[['SK_ID_CURR','SK_ID_PREV','NAME_CONTRACT_STATUS']][
    CCBal['MONTHS_BALANCE']>=-24][
        CCBal['NAME_CONTRACT_STATUS']=='Active'
    ].drop_duplicates().sort_values(by=['SK_ID_CURR','SK_ID_PREV'])

temp2 = temp.groupby('SK_ID_CURR').agg(
    count=('SK_ID_PREV','count')
).reset_index()

temp2.query('count>1')

C:\Users\domjo\AppData\Local\Temp\ipykernel_18992\2356360141.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  temp = CCBal[['SK_ID_CURR','SK_ID_PREV','NAME_CONTRACT_STATUS']][

       SK_ID_CURR  count
79         100259      2
82         100267      2
185        100594      2
228        100763      2
656        102217      2
...           ...    ...
99112      448891      2
99235      449270      2
100072     452256      2
100761     454668      2
101052     455694      2

[416 rows x 2 columns]

Check Previous IDs to see if multiple active contracts occur at same time in last 1 months

In [18]:
temp = CCBal[
    CCBal['MONTHS_BALANCE']==-1][
        CCBal['NAME_CONTRACT_STATUS']=='Active'
    ][['SK_ID_CURR','SK_ID_PREV','NAME_CONTRACT_STATUS']].drop_duplicates().sort_values(by=['SK_ID_CURR','SK_ID_PREV'])

temp2 = temp.groupby('SK_ID_CURR').agg(
    count=('SK_ID_PREV','count')
).reset_index()

temp2.query('count > 1')

C:\Users\domjo\AppData\Local\Temp\ipykernel_18992\90034963.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  temp = CCBal[

      SK_ID_CURR  count
2547      116511      2
9884      163057      2
10232     165107      2
14968     195289      2
17099     208476      2
22696     242658      2
23396     247312      2
23929     250820      2
24043     251549      2
26010     263969      2
32300     303407      2
38409     341822      2
51184     422125      2

In [10]:
# & (CCBal['SK_ID_PREV']=='1748913')
temp = CCBal[(CCBal['SK_ID_CURR']=='120076') ].sort_values(by=['SK_ID_PREV','MONTHS_BALANCE'])[['MONTHS_BALANCE','SK_ID_PREV','AMT_BALANCE','AMT_CREDIT_LIMIT_ACTUAL','AMT_DRAWINGS_CURRENT','AMT_PAYMENT_CURRENT','AMT_PAYMENT_TOTAL_CURRENT','AMT_RECIVABLE','AMT_TOTAL_RECEIVABLE']]
temp

,MONTHS_BALANCE,SK_ID_PREV,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_CURRENT,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE
209495,-96,1334824,139260.285,225000,45000.000,53100.000,53100.000,139260.285,139260.285
209496,-95,1334824,8841.960,225000,0.000,132075.000,132075.000,8841.960,8841.960
209497,-94,1334824,139234.185,225000,135000.000,9000.000,9000.000,139234.185,139234.185
209498,-93,1334824,151297.830,225000,53100.000,48600.000,48600.000,151297.830,151297.830
209499,-92,1334824,131530.095,225000,0.000,25267.500,25267.500,131530.095,131530.095
...,...,...,...,...,...,...,...,...,...
209630,-5,2827461,2238.075,247500,87568.020,116751.555,116751.555,0.000,0.000
209631,-4,2827461,35115.570,270000,159504.705,121640.985,121640.985,33545.070,33545.070
209632,-3,2827461,44400.690,270000,113361.300,115655.670,115655.670,42830.190,42830.190
209633,-2,2827461,75788.280,270000,105290.100,101229.345,101229.345,74217.780,74217.780
209634,-1,2827461,67967.955,270000,51267.600,82477.620,82477.620,65717.955,65717.955

In [ ]:
temp = CCBal[CCBal['AMT_TOTAL_RECEIVABLE'] < CCBal['AMT_RECEIVABLE_PRINCIPAL']]

temp[temp['AMT_RECEIVABLE_PRINCIPAL']==0].sort_values(by=['SK_ID_CURR','SK_ID_PREV','MONTHS_BALANCE'], ascending=[True, True, True])

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
38,1843384,100011,-43,804.195,180000,0.0,0.0,0.0,0.0,9000.000,...,-563.355,-563.355,0.0,0,0.0,0.0,32.0,Active,0,0
39,1843384,100011,-42,0.000,180000,0.0,0.0,0.0,0.0,804.195,...,-563.355,-563.355,0.0,0,0.0,0.0,33.0,Active,0,0
40,1843384,100011,-41,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,-563.355,-563.355,0.0,0,0.0,0.0,33.0,Active,0,0
41,1843384,100011,-40,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,-563.355,-563.355,0.0,0,0.0,0.0,33.0,Active,0,0
42,1843384,100011,-39,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,-563.355,-563.355,0.0,0,0.0,0.0,33.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840229,1595171,456247,-49,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,-520.605,-520.605,0.0,0,0.0,0.0,32.0,Active,0,0
3840230,1595171,456247,-48,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,-520.605,-520.605,0.0,0,0.0,0.0,32.0,Active,0,0
3840231,1595171,456247,-47,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,-520.605,-520.605,0.0,0,0.0,0.0,32.0,Active,0,0
3840232,1595171,456247,-46,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,-520.605,-520.605,0.0,0,0.0,0.0,32.0,Active,0,0
3840233,1595171,456247,-45,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,-520.605,-520.605,0.0,0,0.0,0.0,32.0,Active,0,0

In [ ]:
zero_receivable = CCBal[CCBal['AMT_TOTAL_RECEIVABLE'] == 0][['AMT_PAYMENT_CURRENT', 'AMT_DRAWINGS_CURRENT', 'AMT_BALANCE']]

zero_receivable[zero_receivable['AMT_BALANCE']==0][zero_receivable['AMT_PAYMENT_CURRENT']>0]

C:\Users\domjo\AppData\Local\Temp\ipykernel_11732\776576759.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zero_receivable[zero_receivable['AMT_BALANCE']==0][zero_receivable['AMT_PAYMENT_CURRENT']>0]

         AMT_PAYMENT_CURRENT  AMT_DRAWINGS_CURRENT  AMT_BALANCE
43                   563.355                   0.0          0.0
44                   563.355                   0.0          0.0
45                   563.355                   0.0          0.0
46                   563.355                   0.0          0.0
47                   563.355                   0.0          0.0
...                      ...                   ...          ...
3840272              520.605                   0.0          0.0
3840273              520.605                   0.0          0.0
3840274              520.605                   0.0          0.0
3840275              520.605                   0.0          0.0
3840276              520.605                   0.0          0.0

[1084502 rows x 3 columns]

In [13]:
zero_receivable[zero_receivable['AMT_BALANCE']==0][zero_receivable['AMT_DRAWINGS_CURRENT']==0]#[zero_receivable['AMT_PAYMENT_CURRENT']>0]

C:\Users\domjo\AppData\Local\Temp\ipykernel_11732\675974210.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zero_receivable[zero_receivable['AMT_BALANCE']==0][zero_receivable['AMT_DRAWINGS_CURRENT']==0]#[zero_receivable['AMT_PAYMENT_CURRENT']>0]

         AMT_PAYMENT_CURRENT  AMT_DRAWINGS_CURRENT  AMT_BALANCE
0                        NaN                   0.0          0.0
1                        NaN                   0.0          0.0
2                        NaN                   0.0          0.0
3                        NaN                   0.0          0.0
4                        NaN                   0.0          0.0
...                      ...                   ...          ...
3840295                  NaN                   0.0          0.0
3840296                  NaN                   0.0          0.0
3840297                  NaN                   0.0          0.0
3840298                  NaN                   0.0          0.0
3840299                  NaN                   0.0          0.0

[2028599 rows x 3 columns]

`AMT_DRAWINGS_CURRENT` = 0 should imply `AMT_DRAWINGS_ATM_CURRENT` = 0, `AMT_DRAWINGS_POS_CURRENT` = 0 etc

In [ ]:
CCBal[CCBal['AMT_DRAWINGS_CURRENT'] == 0][CCBal['AMT_DRAWINGS_ATM_CURRENT']>0] # AMT_DRAWINGS_OTHER_CURRENT AMT_DRAWINGS_POS_CURRENT

C:\Users\domjo\AppData\Local\Temp\ipykernel_18992\3817334182.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  CCBal[CCBal['AMT_DRAWINGS_CURRENT'] == 0][CCBal['AMT_DRAWINGS_ATM_CURRENT']>0]

Empty DataFrame
Columns: [SK_ID_PREV, SK_ID_CURR, MONTHS_BALANCE, AMT_BALANCE, AMT_CREDIT_LIMIT_ACTUAL, AMT_DRAWINGS_ATM_CURRENT, AMT_DRAWINGS_CURRENT, AMT_DRAWINGS_OTHER_CURRENT, AMT_DRAWINGS_POS_CURRENT, AMT_INST_MIN_REGULARITY, AMT_PAYMENT_CURRENT, AMT_PAYMENT_TOTAL_CURRENT, AMT_RECEIVABLE_PRINCIPAL, AMT_RECIVABLE, AMT_TOTAL_RECEIVABLE, CNT_DRAWINGS_ATM_CURRENT, CNT_DRAWINGS_CURRENT, CNT_DRAWINGS_OTHER_CURRENT, CNT_DRAWINGS_POS_CURRENT, CNT_INSTALMENT_MATURE_CUM, NAME_CONTRACT_STATUS, SK_DPD, SK_DPD_DEF, UTILIZATION_RATIO, PAYMENT_RATIO, DRAWING_TO_PYMNT_RATIO, INT_COVERAGE_RATIO, POS_DRAWING_AMT_RATIO, ATM_DRAWING_AMT_RATIO, POS_DRAWING_CNT_RATIO, ATM_DRAWING_CNT_RATIO, DPD, DPD_UTP]
Index: []

[0 rows x 33 columns]

Impute data

In [24]:
CCBal.loc[(CCBal['AMT_DRAWINGS_CURRENT'] == 0) & (CCBal['AMT_DRAWINGS_ATM_CURRENT'].isna()), 'AMT_DRAWINGS_ATM_CURRENT'] = 0
CCBal.loc[(CCBal['AMT_DRAWINGS_CURRENT'] == 0) & (CCBal['AMT_DRAWINGS_OTHER_CURRENT'].isna()), 'AMT_DRAWINGS_OTHER_CURRENT'] = 0
CCBal.loc[(CCBal['AMT_DRAWINGS_CURRENT'] == 0) & (CCBal['AMT_DRAWINGS_POS_CURRENT'].isna()), 'AMT_DRAWINGS_POS_CURRENT'] = 0

In [29]:
CCBal[CCBal['AMT_DRAWINGS_CURRENT'] > 0][CCBal['AMT_DRAWINGS_ATM_CURRENT'] > 0] # AMT_DRAWINGS_OTHER_CURRENT AMT_DRAWINGS_POS_CURRENT

C:\Users\domjo\AppData\Local\Temp\ipykernel_18992\4122397814.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  CCBal[CCBal['AMT_DRAWINGS_CURRENT'] > 0][CCBal['AMT_DRAWINGS_ATM_CURRENT'] > 0] # AMT_DRAWINGS_OTHER_CURRENT AMT_DRAWINGS_POS_CURRENT

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,UTILIZATION_RATIO,PAYMENT_RATIO,DRAWING_TO_PYMNT_RATIO,INT_COVERAGE_RATIO,POS_DRAWING_AMT_RATIO,ATM_DRAWING_AMT_RATIO,POS_DRAWING_CNT_RATIO,ATM_DRAWING_CNT_RATIO,DPD,DPD_UTP
6,1843384,100011,-75,189000.000,180000,180000.0,180000.0,0.0,0.0,NaN,...,105.000000,0.000000,NaN,NaN,0.0,100.0,0.0,100.0,0,0
86,2038692,100013,-90,161420.220,157500,157500.0,157500.0,0.0,0.0,NaN,...,102.489029,0.000000,NaN,NaN,0.0,100.0,0.0,100.0,0,0
93,2038692,100013,-83,154471.095,157500,148500.0,148500.0,0.0,0.0,0.00,...,98.076886,0.000000,NaN,NaN,0.0,100.0,0.0,100.0,0,0
96,2038692,100013,-80,137260.845,157500,130500.0,130500.0,0.0,0.0,1078.56,...,87.149743,0.000000,NaN,NaN,0.0,100.0,0.0,100.0,0,0
98,2038692,100013,-78,151663.770,157500,22500.0,22500.0,0.0,0.0,7875.00,...,96.294457,5.601761,250.0,61.587,0.0,100.0,0.0,100.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840199,1595171,456247,-79,4143.420,180000,6750.0,6750.0,0.0,0.0,0.00,...,2.301900,0.000000,NaN,NaN,0.0,100.0,0.0,100.0,0,0
3840202,1595171,456247,-76,96776.640,180000,90000.0,90000.0,0.0,0.0,0.00,...,53.764800,0.092911,100000.0,7580.900,0.0,100.0,0.0,100.0,0,0
3840208,1595171,456247,-70,1120.500,180000,450.0,450.0,0.0,0.0,0.00,...,0.622500,NaN,NaN,NaN,0.0,100.0,0.0,100.0,0,0
3840300,1794451,456250,-12,181993.500,180000,171000.0,171000.0,0.0,0.0,0.00,...,101.107500,0.000000,NaN,NaN,0.0,100.0,0.0,100.0,0,0
3840301,1794451,456250,-11,200208.915,180000,9000.0,9000.0,0.0,0.0,0.00,...,111.227175,0.000000,NaN,NaN,0.0,100.0,0.0,100.0,0,0

`AMT_PAYMENT_TOTAL_CURRENT` is never nan so use that instead of `AMT_PAYMENT_CURRENT`

In [31]:
CCBal.loc[(CCBal['CNT_DRAWINGS_CURRENT'] == 0) & (CCBal['CNT_DRAWINGS_ATM_CURRENT'].isna()), 'CNT_DRAWINGS_ATM_CURRENT'] = 0
CCBal.loc[(CCBal['CNT_DRAWINGS_CURRENT'] == 0) & (CCBal['CNT_DRAWINGS_POS_CURRENT'].isna()), 'CNT_DRAWINGS_POS_CURRENT'] = 0
CCBal.loc[(CCBal['CNT_DRAWINGS_CURRENT'] == 0) & (CCBal['CNT_DRAWINGS_OTHER_CURRENT'].isna()), 'CNT_DRAWINGS_OTHER_CURRENT'] = 0

In [ ]:
CCBal['STATUS_FILLED'] = CCBal.groupby('SK_ID_BUREAU')['STATUS'].transform(
    lambda x: x.ffill(limit=3).bfill(limit=3)
)

In [9]:
CCBal['UTILIZATION_RATIO'] = np.where(CCBal['AMT_CREDIT_LIMIT_ACTUAL'] > 0, 
                                      ( CCBal['AMT_BALANCE'] / CCBal['AMT_CREDIT_LIMIT_ACTUAL'] ) * 100, 
                                      np.nan)
CCBal['PAYMENT_RATIO'] = np.where((CCBal['AMT_PAYMENT_TOTAL_CURRENT'] + CCBal['AMT_TOTAL_RECEIVABLE']) > 0 , 
                                  ( CCBal['AMT_PAYMENT_TOTAL_CURRENT'] / (CCBal['AMT_PAYMENT_TOTAL_CURRENT'] + CCBal['AMT_TOTAL_RECEIVABLE']) ) * 100 ,
                                  np.nan)

CCBal['DRAWING_TO_PYMNT_RATIO'] = np.where(CCBal['AMT_PAYMENT_TOTAL_CURRENT'] > 0 , 
                                           ( CCBal['AMT_DRAWINGS_CURRENT'] / CCBal['AMT_PAYMENT_TOTAL_CURRENT'] ) * 100 ,
                                           np.nan)

CCBal['INT_COVERAGE_RATIO']    = np.where(CCBal['AMT_PAYMENT_TOTAL_CURRENT'] > 0 , 
                                          ((CCBal['AMT_TOTAL_RECEIVABLE']-CCBal['AMT_RECEIVABLE_PRINCIPAL']) / CCBal['AMT_PAYMENT_TOTAL_CURRENT'] ) * 100 ,
                                          np.nan)   
CCBal['POS_DRAWING_AMT_RATIO'] = np.where(CCBal['AMT_DRAWINGS_CURRENT'] > 0 , 
                                         (CCBal['AMT_DRAWINGS_POS_CURRENT'] / CCBal['AMT_DRAWINGS_CURRENT'] ) * 100, 
                                          np.nan)

CCBal['ATM_DRAWING_AMT_RATIO'] = np.where(CCBal['AMT_DRAWINGS_CURRENT'] > 0 , 
                                          (CCBal['AMT_DRAWINGS_ATM_CURRENT'] / CCBal['AMT_DRAWINGS_CURRENT'] ) * 100  , 
                                          np.nan)

CCBal['POS_DRAWING_CNT_RATIO'] = np.where(CCBal['CNT_DRAWINGS_CURRENT'] > 0 , 
                                          (CCBal['CNT_DRAWINGS_POS_CURRENT'] / CCBal['CNT_DRAWINGS_CURRENT'] ) * 100, 
                                          np.nan)
  
CCBal['ATM_DRAWING_CNT_RATIO'] = np.where(CCBal['CNT_DRAWINGS_CURRENT'] > 0 , 
                                          ( CCBal['CNT_DRAWINGS_ATM_CURRENT'] / CCBal['CNT_DRAWINGS_CURRENT'] ) * 100, 
                                            np.nan)  

CCBal['DPD'] = ( CCBal['SK_DPD'] >= 7 ) * 1
CCBal['DPD_UTP'] = ( (CCBal['SK_DPD'] >= 1) & (CCBal['AMT_BALANCE'] >= 100) ) * 1

In [10]:
def get_days_to_first_dpd(x):
    
    months_bal = CCBal.loc[x.index][CCBal.loc[x.index,'SK_DPD']>=7]

    if months_bal.shape[0] > 0:
        start_day = CCBal.loc[x.index]['MONTHS_BALANCE'].min()
        end_day = months_bal['MONTHS_BALANCE'].min()
        return (end_day - start_day) * 30
    else:
        return np.nan

In [ ]:
CCBal_Silver = CCBal.groupby('SK_ID_CURR').agg(
    CreditCard_Max_Duration=('MONTHS_BALANCE','min'),
    CreditCard_Count=('SK_ID_PREV','nunique'),
    CreditCard_Avg_Limit=('AMT_CREDIT_LIMIT_ACTUAL','mean'),
    CreditCard_Avg_Balance=('AMT_BALANCE','mean'),
    CreditCard_Avg_Payment=('AMT_PAYMENT_TOTAL_CURRENT','mean'),
    CreditCard_Max_Utilization_Rate=('UTILIZATION_RATIO','mean'),
    CreditCard_Avg_Payment_Rate=('PAYMENT_RATIO','mean'),
    CreditCard_Avg_DrawingToPayment_Rate=('DRAWING_TO_PYMNT_RATIO','mean'),
    CreditCard_Avg_IntCoverage_Rate=('INT_COVERAGE_RATIO','mean'),
    CreditCard_Avg_POSAmt_Rate=('POS_DRAWING_AMT_RATIO','mean'),
    CreditCard_Avg_ATMAmt_Rate=('ATM_DRAWING_AMT_RATIO','mean'),
    CreditCard_Avg_POSCount_Rate=('POS_DRAWING_CNT_RATIO','mean'),
    CreditCard_Avg_ATMCount_Rate=('ATM_DRAWING_CNT_RATIO','mean'),
    CreditCard_Avg_RepaymentCount_Rate=('CNT_INSTALMENT_MATURE_CUM', lambda x: x[x > 0].count()/x.count()),
    CreditCard_DPD=('DPD','max'),
    CreditCard_DPDUTP=('DPD_UTP','max'),
    CreditCard_DaysToDPD=('MONTHS_BALANCE', lambda x: get_days_to_first_dpd(x)),
    CreditCard_DaysinDPD_Rate=('SK_DPD', lambda x: x[x >= 1].count()/x.count() )
).reset_index()