In [24]:
import pandas as pd
import numpy as np

In [25]:
import os
os.getcwd()
os.chdir('a:\\Dominic\\My Projects\\Home Credit\\')

In [26]:
Payments = pd.read_csv('data/Internal/installments_payments.csv')

In [4]:
Payments.shape

(13605401, 8)

In [5]:
Payments.dtypes

SK_ID_PREV                  int64
SK_ID_CURR                  int64
NUM_INSTALMENT_VERSION    float64
NUM_INSTALMENT_NUMBER       int64
DAYS_INSTALMENT           float64
DAYS_ENTRY_PAYMENT        float64
AMT_INSTALMENT            float64
AMT_PAYMENT               float64
dtype: object

In [6]:
Payments = Payments.astype({'SK_ID_PREV': 'string', 'SK_ID_CURR': 'string'})

In [7]:
Payments.sort_values(by=['SK_ID_CURR', 'SK_ID_PREV', 'NUM_INSTALMENT_NUMBER'], inplace=True)

In [8]:
Payments.head(20)

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
1478621,1369693,100001,1.0,1,-1709.0,-1715.0,3951.000,3951.000
2568722,1369693,100001,1.0,2,-1679.0,-1715.0,3951.000,3951.000
3458712,1369693,100001,1.0,3,-1649.0,-1660.0,3951.000,3951.000
2624024,1369693,100001,2.0,4,-1619.0,-1628.0,17397.900,17397.900
1761012,1851984,100001,1.0,2,-2916.0,-2916.0,3982.050,3982.050
3774071,1851984,100001,1.0,3,-2886.0,-2875.0,3982.050,3982.050
3435373,1851984,100001,1.0,4,-2856.0,-2856.0,3980.925,3980.925
2144879,1038818,100002,1.0,1,-565.0,-587.0,9251.775,9251.775
2163032,1038818,100002,1.0,2,-535.0,-562.0,9251.775,9251.775
1675768,1038818,100002,1.0,3,-505.0,-529.0,9251.775,9251.775
3343696,1038818,100002,1.0,4,-475.0,-498.0,9251.775,9251.775
2841063,1038818,100002,1.0,5,-445.0,-468.0,9251.775,9251.775
1807424,1038818,100002,1.0,6,-415.0,-446.0,9251.775,9251.775
3594829,1038818,100002,1.0,7,-385.0,-412.0,9251.775,9251.775
210205,1038818,100002,1.0,8,-355.0,-375.0,9251.775,9251.775
607863,1038818,100002,1.0,9,-325.0,-344.0,9251.775,9251.775
2646927,1038818,100002,1.0,10,-295.0,-312.0,9251.775,9251.775
2785201,1038818,100002,1.0,11,-265.0,-284.0,9251.775,9251.775
504426,1038818,100002,1.0,12,-235.0,-250.0,9251.775,9251.775
699804,1038818,100002,1.0,13,-205.0,-224.0,9251.775,9251.775

Check if `NUM_INSTALMENT_VERSION` keeps changing or not.

In [9]:
Payments['diff'] = Payments.groupby(['SK_ID_PREV'])['NUM_INSTALMENT_VERSION'].diff()

In [23]:
Payments.query('diff < 0')

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,LATE_PAYMENT_DAYS,INSTALLMENT_RATIO,diff
3645063,2480304,100012,1.0,1,-477.0,-487.0,9482.355,58687.245,-10.0,0.161574,-1.0
471180,1620327,100019,1.0,6,-744.0,-750.0,10518.615,44369.280,-6.0,0.237070,-1.0
2376255,1390369,100034,1.0,1,-569.0,-584.0,22430.430,58500.000,-15.0,0.383426,-1.0
561623,1077565,100039,1.0,1,-665.0,-695.0,52513.515,225000.000,-30.0,0.233393,-1.0
3582969,1636219,100056,2.0,101,-2714.0,-2710.0,1350.000,1350.000,4.0,1.000000,-1.0
...,...,...,...,...,...,...,...,...,...,...,...
12084787,1112768,456202,2.0,11,-293.0,-297.0,21001.500,37494.000,-4.0,0.560130,-1.0
13259241,1333058,456202,1.0,1,-271.0,-297.0,7147.890,18000.000,-26.0,0.397105,-1.0
12052388,2508396,456225,2.0,101,-655.0,-588.0,1350.000,1350.000,67.0,1.000000,-6.0
12067114,2414642,456234,2.0,101,-862.0,-854.0,1350.000,1350.000,8.0,1.000000,-1.0
11721916,2631384,456255,1.0,1,-756.0,-768.0,54022.140,669251.655,-12.0,0.080720,-1.0

In [10]:
Payments[Payments['SK_ID_CURR'] == '184693'][Payments['SK_ID_PREV']== '2234264'] #.sort_values(by='NUM_INSTALMENT_NUMBER', ascending=True)

C:\Users\domjo\AppData\Local\Temp\ipykernel_33104\642422089.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  Payments[Payments['SK_ID_CURR'] == '184693'][Payments['SK_ID_PREV']== '2234264'] #.sort_values(by='NUM_INSTALMENT_NUMBER', ascending=True)

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,diff
2193694,2234264,184693,1.0,1,-649.0,-653.0,17713.125,17713.125,NaN
3756874,2234264,184693,2.0,2,-619.0,-619.0,21125.655,38838.780,1.0
3756875,2234264,184693,1.0,2,-619.0,-619.0,17713.125,38838.780,-1.0
2091088,2234264,184693,3.0,3,-589.0,-584.0,15083.055,15083.055,2.0
1253334,2234264,184693,3.0,4,-559.0,-570.0,15083.055,15083.055,0.0
2054222,2234264,184693,3.0,5,-529.0,-528.0,15083.055,15083.055,0.0
1679015,2234264,184693,3.0,6,-499.0,-500.0,15083.055,15083.055,0.0
1651697,2234264,184693,3.0,7,-469.0,-469.0,15083.055,15083.055,0.0
634648,2234264,184693,3.0,8,-439.0,-438.0,15083.055,15083.055,0.0
2020721,2234264,184693,3.0,9,-409.0,-415.0,15083.055,15083.055,0.0
531069,2234264,184693,3.0,10,-379.0,-385.0,15083.055,15083.055,0.0
6,2234264,184693,4.0,11,-349.0,-352.0,29432.295,29432.295,1.0

In [14]:
temp = Payments[Payments['SK_ID_CURR'] == '184693'][Payments['SK_ID_PREV']== '2234264'] #.sort_values(by='NUM_INSTALMENT_NUMBER', ascending=True)

C:\Users\domjo\AppData\Local\Temp\ipykernel_33104\2410630109.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  temp = Payments[Payments['SK_ID_CURR'] == '184693'][Payments['SK_ID_PREV']== '2234264'] #.sort_values(by='NUM_INSTALMENT_NUMBER', ascending=True)

In [11]:
def get_payment_freq(x):
    approved = full_df.loc[x.index, 'NAME_CONTRACT_STATUS'] == 'Approved'
    return x[approved].iloc[0] if approved.any() else np.nan

In [19]:
Payments['LATE_PAYMENT_DAYS'] = Payments['DAYS_ENTRY_PAYMENT'] - Payments['DAYS_INSTALMENT']

Payments['INSTALLMENT_RATIO'] = np.where(Payments['AMT_PAYMENT'] > 0 ,
                                         Payments['AMT_INSTALMENT'] / Payments['AMT_PAYMENT'] ,
                                         np.nan)
Payments['LATE_PAYMENT_DAYS_LASTYEAR'] = np.where(Payments['DAYS_ENTRY_PAYMENT'] >= -365,
                                                 Payments['LATE_PAYMENT_DAYS'],
                                                 np.nan)

In [20]:
Payments_Silver = Payments.groupby(['SK_ID_CURR', 'SK_ID_PREV']).agg(
    PMNT_INSTLMT_VRSN_CHANGES_COUNT = ('NUM_INSTALMENT_VERSION', lambda x: x.nunique() ),
    PMNT_INSTLMT_DURATION_DAYS = ('DAYS_ENTRY_PAYMENT', lambda x: x.max() - x.min() + 1),
    PMNT_AVG_INSTALLMENT_FREQ = ('DAYS_ENTRY_PAYMENT', lambda x: pd.Series(x.unique()).sort_values().diff().mean() if len(x) > 1 else np.nan),
    PMNT_AVG_LATE_DAYS = ('LATE_PAYMENT_DAYS', lambda x: x.mean() if len(x) > 0 else np.nan),
    PMNT_AVG_LATE_DAYS_LASTYEAR = ('LATE_PAYMENT_DAYS_LASTYEAR', lambda x: x.notna().mean()),
    PMNT_AVG_INSTALLMENT_RATIO = ('INSTALLMENT_RATIO', lambda x: x.mean() if len(x) > 0 else np.nan),
    PMNT_NUM_INSTALMENTS = ('NUM_INSTALMENT_NUMBER', 'count'),
    PMNT_NUM_INSTALMENTS_LASTYEAR = ('DAYS_ENTRY_PAYMENT', lambda x:  x[x >= -365].count() if len(x) > 0 else np.nan)
).reset_index()

`PMNT_AVG_INSTALLMENT_FREQ` the average days between payments, is negative in few cases. This is because in some IDs, the `DAYS_ENTRY_PAYMENT` is decreasng with Installment Number , ie higher installment number indicates an earlier payment rather than a later payment. `NUM_INSTALMENT_NUMBER` is not in correct order, need to sort data based on `DAYS_ENTRY_PAYMENT`.

In [23]:
Payments_Gold = Payments_Silver.groupby(['SK_ID_CURR']).agg(
    PMNT_INSTLMT_VRSN_AVG_CHANGES = ('PMNT_INSTLMT_VRSN_CHANGES_COUNT', 'mean'),
    PMNT_INSTLMT_VRSN_MAX_CHANGES = ('PMNT_INSTLMT_VRSN_CHANGES_COUNT', 'max'),
    PMNT_INSTLMT_VRSN_MEDIAN_CHANGES = ('PMNT_INSTLMT_VRSN_CHANGES_COUNT', 'median'),

    PMNT_INSTLMT_DURATION_DAYS = ('PMNT_INSTLMT_DURATION_DAYS', 'mean'),
    PMNT_INSTLMT_DURATION_MAX_DAYS = ('PMNT_INSTLMT_DURATION_DAYS', 'max'),
    PMNT_INSTLMT_DURATION_MEDIAN_DAYS = ('PMNT_INSTLMT_DURATION_DAYS', 'median'),

    PMNT_AVG_AVG_INSTALLMENT_FREQ = ('PMNT_AVG_INSTALLMENT_FREQ', 'mean'),
    PMNT_MAX_AVG_INSTALLMENT_FREQ = ('PMNT_AVG_INSTALLMENT_FREQ', 'max'),
    PMNT_MEDIAN_AVG_INSTALLMENT_FREQ = ('PMNT_AVG_INSTALLMENT_FREQ', 'median'),

    PMNT_AVG_LATE_DAYS = ('PMNT_AVG_LATE_DAYS', 'mean'),
    PMNT_MAX_LATE_DAYS = ('PMNT_AVG_LATE_DAYS', 'max'),
    PMNT_MEDIAN_LATE_DAYS = ('PMNT_AVG_LATE_DAYS', 'median'),

    PMNT_AVG_AVG_LATE_DAYS_LASTYEAR = ('PMNT_AVG_LATE_DAYS_LASTYEAR', 'mean'),
    PMNT_MAX_AVG_LATE_DAYS_LASTYEAR = ('PMNT_AVG_LATE_DAYS_LASTYEAR', 'max'),
    PMNT_MEDIAN_AVG_LATE_DAYS_LASTYEAR = ('PMNT_AVG_LATE_DAYS_LASTYEAR', 'median'),

    PMNT_AVG_INSTALLMENT_RATIO = ('PMNT_AVG_INSTALLMENT_RATIO', 'mean'),
    PMNT_MEDIAN_INSTALLMENT_RATIO = ('PMNT_AVG_INSTALLMENT_RATIO', 'median'),

    PMNT_AVG_NUM_INSTALMENTS = ('PMNT_NUM_INSTALMENTS', 'mean'),
    PMNT_MAX_NUM_INSTALMENTS = ('PMNT_NUM_INSTALMENTS', 'max'),
    PMNT_MEDIAN_NUM_INSTALMENTS = ('PMNT_NUM_INSTALMENTS', 'median'),

    PMNT_AVG_NUM_INSTALMENTS_LASTYEAR = ('PMNT_NUM_INSTALMENTS_LASTYEAR', 'mean'),
    PMNT_MAX_NUM_INSTALMENTS_LASTYEAR = ('PMNT_NUM_INSTALMENTS_LASTYEAR', 'max'),
    PMNT_MEDIAN_NUM_INSTALMENTS_LASTYEAR = ('PMNT_NUM_INSTALMENTS_LASTYEAR', 'median')
).reset_index()